on:
  workflow_call:
    inputs:
      deploy:
        required: true
        type: boolean

jobs:
  run:
    name: Deploy Application
    runs-on: ubuntu-latest
    container: node:20 # keep version synced w/ serverless.yaml file
    steps:
      - name: Get AWS credentials
        if: inputs.deploy == true
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.SERVERLESS_AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install npm dependencies
        run: npm ci
      - name: Install serverless framework
        run: npm install -g serverless
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Deploy
        if: inputs.deploy == true
        run: npm run deploy
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
